### PR TITLE
Add documentation page for physical interactions

### LINKED ISSUE #14: Add PHI-Canto specific documentation for physical interactions
https://canto.phi-base.org/docs/physical_interaction_annotation

@jseager7 whilst writing the PHI-Canto manuscript I was thinking about the best way to illustrate the Physical interaction annotations. My two thoughts were either
1) as another supplementary file
2) as a screenshot in the Help documentation.

I think my preference would be option 2 as future users may just look at the Help and not the manuscript.

Whilst writing up the section on disease names I noticed that we have such good screenshots in the Help documentation that it seems best to direct readers here rather than generate an additional supplementary file. https://canto.phi-base.org/docs/disease_annotation

### PR DESCRIPTION
**Pull request by jseager7**
(Closes #14)

@CuzickA Here's the changes required to show a screenshot on the 'Curating physical interactions' page. I've done some more edits to the text so that it more accurately describes the workflow in pathogen–host mode. Please read through and let me know if there's anything else that needs updating.

You can see the documentation here: [physical_interaction_annotation.md](https://github.com/PHI-base/canto-docs/blob/97e0e6a9f502d080196f17795852ab4c895635d3/docs/physical_interaction_annotation.md)

### CODE REVIEW

**Comment by jseager7** [comment]
@CuzickA I just remembered your request for removing the comment in the physical interaction example image. I forgot to do this, but it's easy to fix if you're sure you want the comment removed.

Personally, I'm not sure it matters if the comment is left in, since the image makes it clear that it's only a comment. The documentation also mentions the fact you can add comments:

> After selecting the first organism, the rest of the form fields will appear, including a text field for optional comments.

so maybe it is better to show this in the example image.

**Comment by CuzickA** [comment]
Thanks @jseager7 
The reason I wanted to omit the comment in this case is that the three different methods were used to show this physical interaction and ideally this would have resulted in three annotations with different evidence codes. The comment may dissuade curators from doing this properly.

I feel we are missing some clarifying text here...

_When you choose 'Physical interaction', a popup appears with a dropdown menu for the organism(s) involved in the interaction. To curate an intraspecies (or intra-organism) interaction, you can select the same organism in both fields. After selecting the first organism, the rest of the form fields will appear, including a text field for optional comments.

Choose the gene for the first organism in the 'Gene' field and the gene for the interacting organism in the 'Interacting gene' field. Choose an evidence type from the 'Interaction type' dropdown menu. Some evidence types have a brief description that indicates their directionality. Further information on evidence supporting physical interactions, including examples of experiment types in each category, is available on the BioGRID help wiki and in the Directionality section below._

I think we need some clear text stating that it is possible to annotate an intraspecies (or intra-organism) physical interaction and also interspecies (eg pathogen and host species) physical interaction.

**Comment by CuzickA** [comment]
Just re-read and realise that 'the organism(s) involved in the interaction.' would cover intra and inter species.

I still think it would be clearer if there was a sentence saying that both intra and inter species physical interaction annotations can be made.

**Comment by jseager7** [comment]
@CuzickA Here's the amended text clarifying interspecies interactions (additions in bold).

> When you choose 'Physical interaction', a popup appears with a dropdown menu for the organism(s) involved in the interaction. **To curate an interspecies interaction, select different organisms for each field. To curate an intraspecies (or intra-organism) interaction, select the same organism in both fields. Note that only organisms of the species added to the curation session can be selected.** After selecting the first organism, the rest of the form fields will appear, including a text field for optional comments.

The third sentence could be shortened to "Note that only species added to the curation session can be selected." I'm not sure if we should prefer 'organisms' or 'species' for the wording of the whole paragraph.

**Comment by CuzickA** [comment]
> @CuzickA Here's the amended text clarifying interspecies interactions (additions in bold).
> 
> > When you choose 'Physical interaction', a popup appears with a dropdown menu for the organism(s) involved in the interaction. **To curate an interspecies interaction, select different organisms for each field. To curate an intraspecies (or intra-organism) interaction, select the same organism in both fields. Note that only organisms of the species added to the curation session can be selected.** After selecting the first organism, the rest of the form fields will appear, including a text field for optional comments.
> 
> The third sentence could be shortened to "Note that only species added to the curation session can be selected." I'm not sure if we should prefer 'organisms' or 'species' for the wording of the whole paragraph.

This is looking good. 
I think that 'species' reads better throughout the whole paragraph. Please could you make the change and just keep organism in 'intra-organism' text. It would also then make more sense to have the shortened text "Note that only species added to the curation session can be selected."

**Comment by jseager7** [comment]
@CuzickA I've made your requested changes. The latest version of the documentation can be seen here: [physical_interaction_annotation.md](https://github.com/PHI-base/canto-docs/blob/4d298ff65b963a68ab108bf34afa593f194e8e83/docs/physical_interaction_annotation.md)

Note that I've removed the comment column from the example image as well.

**Comment by CuzickA** [comment]
Looks good, thanks @jseager7

**Pull request merged**
