### PR TITLE
Add documentation for disease annotations

### PR DESCRIPTION
**Pull request by jseager7**
This pull request will add a new page for the 'Disease name' annotation type. I've taken the decision not to include the disease annotation type in the 'Curating phenotypes' page because it's not a phenotype annotation.

Follow the link below to see the latest draft of the documentation page for disease annotations:

https://github.com/PHI-base/canto-docs/blob/disease_annotation/docs/disease_annotation.md

@CuzickA I have a few questions about the text I've written:

* I've chosen to use the NCIT's definition of 'infectious disease' as PHI-base's definition of disease. Hopefully it won't be too controversial, but I recommend you double check it just in case there are any problems:

  > A disorder resulting from the presence and activity of a microbial, viral, fungal, or parasitic agent. It can be transmitted by direct or indirect contact.

* (**resolved**) The phenotype documentation has some caveats relating to the temporal aspects of extensions: specifically, that multiple extensions on the same annotation are taken to occur simultaneously, as opposed to occurring at separate times. Is this distinction worth preserving for diseases? For example, in the hypothetical case of a pathogen that can cause the same disease at two (or more) separate anatomical locations (tissue types), should each location have its own disease annotation, or should we curate every possible anatomical location in one disease annotation? Basically, do we need to distinguish simultaneous (systemic) infection of multiple anatomical locations from individual infection of multiple possible infection sites?

### CODE REVIEW

**Comment by jseager7** [comment]
@CuzickA In order to add images for the Disease annotation help page, I need an example of a metagenotype I can use for the disease annotation. I also need a suggestion for a term from PHIDO that I should use, and a tissue type. We can probably just pick one disease annotation from an existing session.

**Comment by CuzickA** [comment]
How about this one https://canto.phi-base.org/curs/d7b3170ded99924f/ro/

image

**Comment by jseager7** [comment]
That's great, thanks.

**Comment by jseager7** [comment]
@CuzickA I think the disease annotation page is ready to be reviewed, when you have time. Here's a link to the latest draft:

https://github.com/PHI-base/canto-docs/blob/disease_annotation/docs/disease_annotation.md

Please let me know if it looks okay. If there are no changes required then I'll merge this into the repository and enable it on PHI-Canto.

**Pull request merged**
